# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 386)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inputFileName = QtWidgets.QLineEdit(self.frame)
        self.inputFileName.setGeometry(QtCore.QRect(100, 30, 271, 20))
        self.inputFileName.setObjectName("inputFileName")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.label.setObjectName("label")
        self.browser = QtWidgets.QPushButton(self.frame)
        self.browser.setGeometry(QtCore.QRect(380, 29, 61, 23))
        self.browser.setObjectName("browser")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 111, 71, 16))
        self.label_2.setObjectName("label_2")
        self.filterColunm = QtWidgets.QComboBox(self.frame)
        self.filterColunm.setGeometry(QtCore.QRect(100, 110, 271, 22))
        self.filterColunm.setObjectName("filterColunm")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_3.setObjectName("label_3")
        self.filterFormat = QtWidgets.QComboBox(self.frame)
        self.filterFormat.setGeometry(QtCore.QRect(100, 150, 101, 22))
        self.filterFormat.setObjectName("filterFormat")
        self.filterFormat.addItem("")
        self.filterFormat.addItem("")
        self.filterFormat.addItem("")
        self.startValue = QtWidgets.QLineEdit(self.frame)
        self.startValue.setGeometry(QtCore.QRect(100, 190, 171, 20))
        self.startValue.setObjectName("startValue")
        self.endValue = QtWidgets.QLineEdit(self.frame)
        self.endValue.setGeometry(QtCore.QRect(290, 190, 151, 20))
        self.endValue.setObjectName("endValue")
        self.filterBtn = QtWidgets.QPushButton(self.frame)
        self.filterBtn.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.filterBtn.setObjectName("filterBtn")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 233, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selectedRows = QtWidgets.QLabel(self.frame)
        self.selectedRows.setGeometry(QtCore.QRect(250, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectedRows.setFont(font)
        self.selectedRows.setText("")
        self.selectedRows.setObjectName("selectedRows")
        self.saveBtn = QtWidgets.QPushButton(self.frame)
        self.saveBtn.setGeometry(QtCore.QRect(20, 320, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.outputFileName = QtWidgets.QLineEdit(self.frame)
        self.outputFileName.setGeometry(QtCore.QRect(190, 320, 181, 20))
        self.outputFileName.setObjectName("outputFileName")
        self.importBtn = QtWidgets.QPushButton(self.frame)
        self.importBtn.setGeometry(QtCore.QRect(380, 70, 61, 23))
        self.importBtn.setObjectName("importBtn")
        self.importedCsvFile = QtWidgets.QLabel(self.frame)
        self.importedCsvFile.setGeometry(QtCore.QRect(100, 70, 271, 20))
        self.importedCsvFile.setText("")
        self.importedCsvFile.setObjectName("importedCsvFile")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 320, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(380, 320, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CSV Convert"))
        self.label.setText(_translate("Dialog", "Input CSV File:"))
        self.browser.setText(_translate("Dialog", "Browser"))
        self.label_2.setText(_translate("Dialog", "Filter Colunm:"))
        self.label_3.setText(_translate("Dialog", "Filter Format:"))
        self.filterFormat.setItemText(0, _translate("Dialog", "Range"))
        self.filterFormat.setItemText(1, _translate("Dialog", "Same"))
        self.filterFormat.setItemText(2, _translate("Dialog", "Like"))
        self.filterBtn.setText(_translate("Dialog", "Filter"))
        self.label_4.setText(_translate("Dialog", "Filtered Rows: "))
        self.saveBtn.setText(_translate("Dialog", "Save as"))
        self.importBtn.setText(_translate("Dialog", "Import"))
        self.label_5.setText(_translate("Dialog", "output/"))
        self.label_6.setText(_translate("Dialog", ".csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
